### ISSUE TITLE
Не работает setup.py

### ISSUE THREAD

**Issue by OlimpiiaART** [xD1rty/dnevniklib#5]
выдаёт такую ошибку
```
Traceback (most recent call last):
  File "C:\Users\Olimpiia\Downloads\dnevniklib-2.0\setup.py", line 3, in <module>
    long_description = fh.read()
  File "C:\Users\Olimpiia\AppData\Local\Programs\Python\Python39\lib\encodings\cp1251.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 2810: character maps to <undefined>
```

я убрал long_description, далее была такая ошибка
```
C:\Scripts\ven\lib\site-packages\setuptools\dist.py:530: UserWarning: Normalizing '2.0.0b' to '2.0.0b0'
  warnings.warn(tmpl.format(**locals()))
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied
```

**Comment by xD1rty** [comment]
Здравствуйте! спасибо за комментарий! Setup.py был оптимизирован для PyPi, так что замените
2.0.0b на 2.0.0b0
